### ISSUE TITLE
Official distribution for 1.17.1?

### ISSUE THREAD

**Issue by sudofox** [mega12345mega/NBT-Editor#1]
I'm super happy this thing exists now!

I was able to tweak the fabric.mod.json to get it to work in 1.17.1. After using it for a few minutes, I'm not seeing any real issues/bugs (so far).

Would it be possible for you to put up official builds for that version? I'm still playing primarily on 1.17.1 with ViaFabric for 1.18.x support

**Comment by sudofox** [comment]
Also, I noticed that the client-side item catalog (that is COOL by the way!) has a typo of "Destory", not gonna bother making a separate issue for that

**Comment by mega12345mega** [comment]
Thanks for your bug report!
I just sent out v1.2.0, which addresses both of these issues.
I can't remember if there was a reason to not support 1.17, but if issues crop up I will try to fix them.
