### ISSUE TITLE
will this be uploaded to Modrinth?

### ISSUE THREAD

**Issue by HyperSoop** [mega12345mega/NBT-Editor#10]
title

Modrinth is the new mod upload platform that's kinda cool and stuff and has better user/creator experience, at https://modrinth.com/
personally wanna say that this is the best NBT editor mod that i've ever used, and i wish you good luck in development

**Comment by mega12345mega** [comment]
Sounds like a good idea, so I've gone ahead and uploaded it: [https://modrinth.com/mod/nbt-editor](https://modrinth.com/mod/nbt-editor) (it currently seems to be "processing", so I don't know if you can access it yet)
I believe I have copied over all the information correctly - though I might have missed something.
I don't currently plan on uploading all the previous versions, though if it starts to have a good number of downloads I might go ahead and do that.
