### ISSUE TITLE
1.20.5/1.20.6?

### ISSUE THREAD

**Issue by ModxVoldHunter** [mega12345mega/NBT-Editor#103]
wonder if those versions will be released

**Comment by mega12345mega** [comment]
I'm planning to support 1.20.5 & 1.20.6, but in the update after next:
- v2.0.0: Server-Side Integration (block & entity editing, + other server stuff)
- v2.0.1: 1.20.5 & 1.20.6 Support
  - I'm also not sure what to do about the client chest, as almost every item will break and need to be updated - I'm planning to upgrade the client chest soon, so the client chest update may also be included to make 1.20.5's client chest make sense (I don't want to automatically update all the items, in-case people want to keep a copy of the old version)

**Comment by Xantrisse** [comment]
> I'm also not sure what to do about the client chest, as almost every item will break and need to be updated - I'm planning to upgrade the client chest soon, so the client chest update may also be included to make 1.20.5's client chest make sense (I don't want to automatically update all the items, in-case people want to keep a copy of the old version)

When removing an item from a client chest, you can invoke code to convert the item from older versions to newer versions. Another option is when putting items into the chest: either keep the current NBT or convert to version 1.20.4 to maintain a uniform way of saving NBT

**Comment by ModxVoldHunter** [comment]
> I'm planning to support 1.20.5 & 1.20.6, but in the update after next:
> - v2.0.0: Server-Side Integration (block & entity editing, + other server stuff)
> - v2.0.1: 1.20.5 & 1.20.6 Support
>   - I'm also not sure what to do about the client chest, as almost every item will break and need to be updated - I'm planning to upgrade the client chest soon, so the client chest update may also be included to make 1.20.5's client chest make sense (I don't want to automatically update all the items, in-case people want to keep a copy of the old version)

Sounds good to me

**Comment by mega12345mega** [comment]
> When removing an item from a client chest, you can invoke code to convert the item from older versions to newer versions. Another option is when putting items into the chest: either keep the current NBT or convert to version 1.20.4 to maintain a uniform way of saving NBT

I haven't actually checked the code, but I imagine converting from 1.20.6 to 1.20.4 would be very difficult, for the same reason worlds can't get downgraded: new features would have to be handed somehow, and (presumably) there isn't a built in system for that that I would be able to re-use - otherwise, that would be the best way to go

**Comment by ModxVoldHunter** [comment]
> I'm planning to support 1.20.5 & 1.20.6, but in the update after next:
> 
> * v2.0.0: Server-Side Integration (block & entity editing, + other server stuff)
> * v2.0.1: 1.20.5 & 1.20.6 Support
>   
>   * I'm also not sure what to do about the client chest, as almost every item will break and need to be updated - I'm planning to upgrade the client chest soon, so the client chest update may also be included to make 1.20.5's client chest make sense (I don't want to automatically update all the items, in-case people want to keep a copy of the old version)

the server-side, i've used the mod on servers and works well, but with the intergration it would probably perform better

**Comment by Maks7594** [comment]
> I'm planning to support 1.20.5 & 1.20.6, but in the update after next:
> 
> * v2.0.0: Server-Side Integration (block & entity editing, + other server stuff)
> * v2.0.1: 1.20.5 & 1.20.6 Support
>   
>   * I'm also not sure what to do about the client chest, as almost every item will break and need to be updated - I'm planning to upgrade the client chest soon, so the client chest update may also be included to make 1.20.5's client chest make sense (I don't want to automatically update all the items, in-case people want to keep a copy of the old version)

about the client chest, you would be able to open it using /oldclientchest or /oldchest or something

**Comment by radmanplays** [comment]
> I'm planning to support 1.20.5 & 1.20.6, but in the update after next:
> 
> * v2.0.0: Server-Side Integration (block & entity editing, + other server stuff)
> * v2.0.1: 1.20.5 & 1.20.6 Support
>   
>   * I'm also not sure what to do about the client chest, as almost every item will break and need to be updated - I'm planning to upgrade the client chest soon, so the client chest update may also be included to make 1.20.5's client chest make sense (I don't want to automatically update all the items, in-case people want to keep a copy of the old version)

release date?

**Comment by mega12345mega** [comment]
> release date?

I have started the final phase of v2.0.0: getting it working in 1.17-1.20.3 instead of just 1.20.4. It is impossible to predict when I will finish, since I typically just keep finding crashes until eventually it stops crashing. (Also, some crashes are very easy to fix, while others could take several hours.)

1.20.5 support is similar; first I have to fix the many errors that are underlined in red, then find all the crashes in 1.20.5, then get it working in 1.17 again. (1.20.6 *shouldn't* involve any code changes, though it is possible due to what was fixed.)

1.21 is the same process for 1.20.5 all over again, but at least NBT wasn't heavily re-thought.

**Comment by Xantrisse** [comment]
Or maybe you should add a menu where the player moves items and then selects the version they want to convert the selected items to, or add a new button on the client chest page that allows you to convert the entire page to other versions. This can be quite difficult, but it's better than automatically updating items or losing unsupported NBT tags.

**Comment by mega12345mega** [comment]
I've now added 1.20.5 & 1.20.6 support in v2.0.1. The client chest pages now include a `DataVersion` tag, and you will be prompted whenever it doesn't match the current version of Minecraft to update the page(s).
