### ISSUE TITLE
Item bugging?

### ISSUE THREAD

**Issue by BNectarie** [mega12345mega/NBT-Editor#112]
Whenever I try to move a item in my inventory or a chest/ender chest any storage part in a multiplayer server it doesn't work and the item if its in slot 1 and I try to move it in slot 2 with 2 or 1 it just teleports back to slot 1 and sometimes in some servers multiplayer it even makes the items disappear for me it seems to just be like that in Minehut servers and the lobbies I haven't tried any other multiplayer servers yet and it works perfectly in multiplayer but it doesn't work in multiplayer
so what should I do??
I also think it affects only me and maybe some other people
It might be because of the huge files of NBT I have in my /chest

**Comment by BNectarie** [comment]
I also think it only affects me and maybe some other people

**Comment by BNectarie** [comment]
For now so I could play multiplayer I turned off the mod

**Comment by BNectarie** [comment]
I tried running the mod alone and now it works perfectly il try to figure out what mod causes the bug

**Comment by zz32k** [comment]
Yeah i'm also experiencing this bug. Works fine in singleplayer and some multiplayer servers but only if I have creative mode.

**Comment by zz32k** [comment]
Fixed it by turning off the no slot restrictions in the config

**Comment by BNectarie** [comment]
il try that aswell thanks for letting me know

**Comment by BNectarie** [comment]
Il try that aswell thanks for letting me know

**Comment by mega12345mega** [comment]
Do you have container related mod(s)? No slot restrictions encodes if it is enabled in the click slot packet, so if that is intercepted by a different mod first, that mod may get confused (this behavior also matches when the server side of NBT Editor was failing to intercept the packet when testing)

**Comment by Clexus** [comment]
I have encountered this bug too, I can't interact with opened inventories in multiplayer in creative mode

**Comment by mega12345mega** [comment]
Has anyone managed to find the mod that NBT Editor is conflicting with?

**Comment by mega12345mega** [comment]
I just found something: it looks like if NBT Editor *isn't* running on the server, the client still tries to tell the server that no slot restrictions is enabled, which confuses the server

Has anyone had this issue while NBT Editor *is* running on the server? (Which would indicate there is also still a mod conflict)

**Comment by Clexus** [comment]
> I just found something: it looks like if NBT Editor _isn't_ running on the server, the client still tries to tell the server that no slot restrictions is enabled, which confuses the server
> 
> Has anyone had this issue while NBT Editor _is_ running on the server? (Which would indicate there is also still a mod conflict)

I don't have it running on my server

**Comment by mega12345mega** [comment]
I believe I have completely fixed this in v2.0.2, but please re-open this issue or open a new one if you find a problem
