### ISSUE TITLE
"Unbreakable" tag has to be written manually

### ISSUE THREAD

**Issue by TabFox-log** [mega12345mega/NBT-Editor#116]
If you want to make an item unbreakable with {Unbreakable:true}, you have to write the not manually, there isn't any button.

**Comment by mega12345mega** [comment]
There is a `/factory unbreakable` (`/f ub` if you have extreme aliases enabled), which toggles the unbreakable tag - are you specifically requesting a respective button on the factories list gui? (There are several factories that don't have gui equivalents, so I would probably add something for all of them)

**Comment by TabFox-log** [comment]
Knowing this, I feel it's unnecessary. Thanks for telling me
