### ISSUE TITLE
Bug: Can't Delete Find

### ISSUE THREAD

**Issue by AlphaLeoli** [mega12345mega/NBT-Editor#119]
I made a typo in the 'find and replace' thing and now when I press backspace it deletes the nbt behind it.
- Minecraft Version: 1.21.1
- NBT Editor Version: 2.0.2.999

**Comment by mega12345mega** [comment]
It looks like this also happens in v2.0.1

**Comment by mega12345mega** [comment]
This has now been fixed in v2.0.2!
