### ISSUE TITLE
Suggestion: Export Selection as NBT

### ISSUE THREAD

**Issue by AlphaLeoli** [mega12345mega/NBT-Editor#121]
There is a `/nbt export file` command, right? Well, when I'm making datapacks it comes up a lot that I include a structure file as a .nbt file. Usually, I just do this by using a structure block and then saving it and then going and getting the file manually. But it would be a lot easier if the command was more like I could do something like `/nbt export area -296 88 -630 -299 84 -624` and then I could just open the file in chat like you have for the file option. Or maybe, if you do `/nbt export area -296 88 -630` and there's a structure block at that position, it will export whatever selection that has.

**Comment by mega12345mega** [comment]
This currently isn't really in the scope of this mod - you could try suggesting this to a mod like World Edit however (World Edit already has this for schematics, so it seems natural to add a structure variant if that doesn't already exist)
