### ISSUE TITLE
Game crashes because the item is not in the range 1-99

### ISSUE THREAD

**Issue by Xantrisse** [mega12345mega/NBT-Editor#122]
After typing "/get item bedrock 100" the game crashes because the item is not in the range 1-99

**Comment by mega12345mega** [comment]
This isn't happening for me, but I might have inadvertently fixed this at some point - are you still able to replicate this on the latest dev build? ([https://github.com/mega12345mega/NBT-Editor/actions/runs/11773796273](https://github.com/mega12345mega/NBT-Editor/actions/runs/11773796273))

**Comment by Xantrisse** [comment]
Unfortunately, I can't check it now because I've already moved to version 1.21.3

**Comment by mega12345mega** [comment]
Then I guess it's safe to assume that it's fixed
