### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by KainGross** [mega12345mega/NBT-Editor#125]
Map<MatrixStack, DrawContext> drawContexts in com.luneruniverse.minecraft.mod.nbteditor.multiversion.MVDrawableHelper does not remove any values due to DrawContext's refers to MatrixStack, causing an infinite map growth with useless objects

![image](https://github.com/user-attachments/assets/f12309fe-f034-4e31-a9a5-33fddee3896d)
![image](https://github.com/user-attachments/assets/bb152adc-1222-44a4-86ca-2bbb03ea5431)
![image](https://github.com/user-attachments/assets/10236746-a4ce-46e0-bf81-ffebf71b2f6e)

**Comment by mega12345mega** [comment]
Nice find! I'll fix this in the next dev build
