### ISSUE TITLE
Bug: nbteditor-2.0.2.999 is incompatible with bobby-5.2.4+mc1.21

### ISSUE THREAD

**Issue by Mat0u5** [mega12345mega/NBT-Editor#126]
Minecraft version: 1.21 (duh)
Mod list:
![image](https://github.com/user-attachments/assets/24869e13-d942-43e2-ae30-9e3d56ccd0c3)

crash report: https://pastebin.com/zgpyrSaJ

Bobby mod site: https://modrinth.com/mod/bobby
Bobby source code: https://github.com/Johni0702/bobby/

I've also tried the two other versions of Bobby for 1.21, and none worked.

I know the error is technically on Bobby's side (as seen from the crash report), but still, thought i should post it here, since this is a dev build, and hopefully you might be able to do something about it too :)

Source code crash walkthrough:
Bobby.onInitializeClient(Bobby.java:83): [here](https://github.com/Johni0702/bobby/blob/3fa716e99f54d41e0704e308bd0d8748e90111ed/src/main/java/de/johni0702/minecraft/bobby/Bobby.java#L83)
Bobby$MaxRenderDistanceConfigHandler.<init>(Bobby.java:240): [here](https://github.com/Johni0702/bobby/blob/3fa716e99f54d41e0704e308bd0d8748e90111ed/src/main/java/de/johni0702/minecraft/bobby/Bobby.java#L240)
Bobby$MaxRenderDistanceConfigHandler.update(Bobby.java:248): [here](https://github.com/Johni0702/bobby/blob/3fa716e99f54d41e0704e308bd0d8748e90111ed/src/main/java/de/johni0702/minecraft/bobby/Bobby.java#L248)
Bobby$MaxRenderDistanceConfigHandler.setMaxRenderDistance(Bobby.java:258): [here](https://github.com/Johni0702/bobby/blob/3fa716e99f54d41e0704e308bd0d8748e90111ed/src/main/java/de/johni0702/minecraft/bobby/Bobby.java#L258)

well when i did the walkthrough, i was so damn confused, like, it crashes on this line:
`SimpleOption<Integer> viewDistance = client.options.getViewDistance();`
client and options are both non null, thats fine, its the .getViewDistance() that causes the crash.
but i mean, what the hell does NBTEditor have to do with render distances, why would Bobby crash because NBTEditor is installed xD

**Comment by mega12345mega** [comment]
A while ago in the Discord, someone mentioned that Bobby requires an older version of the Fabric API - when you installed NBT Editor, did you also have to update Fabric API? If so, try it without NBT Editor
Looking at the error, it seems like the `options` field is null due how Fabric calls mod entrypoints within `MinecraftClient`'s constructor - there shouldn't be anything in my code that messes with the initialization of `options` or the calling of mod entrypoints

**Comment by Mat0u5** [comment]
The game starts up fine with just bobby+fabric api and with nbteditor+fabric api, its the combination of all three that doesnt work.
I mean I've since fixed my problem by modifying Bobby's source code to get around the error, so i don't really need you to fix this, but other people might be experiencing this so...

**Comment by MysticMia** [comment]
I have this issue too, yeah... I'd love to be able to use both at the same time..
