### ISSUE TITLE
Crashes in 1.19.1

### ISSUE THREAD

**Issue by catb0x** [mega12345mega/NBT-Editor#13]
https://crashy.net/9GeoPw3TfrGYOhhRUrBi
Can you add an 1.19.1 version?

**Comment by mega12345mega** [comment]
I hadn't realized it wouldn't work in 1.19.1 - I'll take a look.
It appears to be due to the SendPacketMixin no longer getting added in, which might make it annoying to fix.

**Comment by mega12345mega** [comment]
I've just released v1.6.2 to fix this! Thanks.
