### ISSUE TITLE
Pages not working??

### ISSUE THREAD

**Issue by BNectarie** [mega12345mega/NBT-Editor#136]
I changed from 1.20.4 to 1.21.1 but it required me to update my pages and when I tried to update them it just said error and didn't work at all? idk what could be causing that. I also tried 1.20.6 it still didn't work though

**Comment by BNectarie** [comment]
![image](https://github.com/user-attachments/assets/e74674cd-0acb-4a8e-ad70-6a25c379638d)

**Comment by mega12345mega** [comment]
See [Updating the Client Chest: "Error while updating the client chest!"](https://github.com/mega12345mega/NBT-Editor/wiki/Updating-the-Client-Chest#error-while-updating-the-client-chest)
Let me know if you have any questions, otherwise you can close this issue
