### ISSUE TITLE
Add a feature to get the give command

### ISSUE THREAD

**Issue by SioGabx** [mega12345mega/NBT-Editor#18]
Hello, can you add a command to get the give command of the curent item in hand ?
For exemple i have this (simple exemple):
![image](https://user-images.githubusercontent.com/41244237/190877654-8096aaa5-f7a2-4b13-a7a3-f1d924c9f135.png)

And i want this :
`/give @p oak_sign{AttributeModifiers:[{AttributeName:"generic.armor",Amount:5,Name:"generic.armor",UUID:[I;-122817,14381,23514,-28762]}],display:{Name:'[{"text":"Panneau","italic":false}]',Lore:['[{"text":"Hy ! Your mod is awesome","italic":false}]']},Enchantments:[{id:fire_aspect,lvl:5},{id:sharpness,lvl:10}]} 1`

Can you add something like this ?
Ps: your mod is awsome 👍

**Comment by mega12345mega** [comment]
I was considering making it so the "Expand" button would also work when no tag was selected, at which point it would display the whole compound/list's nbt. (For example, when inside the AttributeModifiers tag, clicking *Expand* would be the equivalent of hitting the back arrow, selecting *AttributeModifiers*, and clicking *Expand*.)

This would also allow you to access the item's entire root tag at once, which could be copied into a /give command.

As an addition, do you think I should also make a dedicated command for this purpose? Something like `/nbt export give`, which would copy the full /give command to your clipboard. It could also have variants like:
* `/nbt export get` - Copies /get item oak_sign{...} 1
* `/nbt export cmdblock` - Gives yourself a command block with the /give command inside

**Comment by SioGabx** [comment]
Having both (the "expand" button and the dedicated command) would be perfect for me ! 
I look forward to your release ! ☺️

**Comment by mega12345mega** [comment]
I have now released v1.9.0, which includes both the expand upgrade and `/nbt export` command!
