### ISSUE TITLE
hey  can you make it so we can put color in the name of items ? if so thank you :)

### ISSUE THREAD

**Issue by hlath43** [mega12345mega/NBT-Editor#19]
hey  can you make it so we can put color in the name of items ? if so thank you :)

**Comment by mega12345mega** [comment]
I'm assuming you're referring to the text box at the top of the /nbt menu?
You can currently add color to item names, but you have to edit the nbt directly.

### Current Method
If you set `display.Name` to `'{"text":"Some Name","color":"red","underlined":"true"}'`, the item will be named to `Some Name`, in red, with an underline.
For the full text format, refer to the official wiki:
[https://minecraft.fandom.com/wiki/Raw_JSON_text_format](https://minecraft.fandom.com/wiki/Raw_JSON_text_format)

### Future Upgrades
While the text box is meant to be similar to an anvil's rename field, I have plans to implement [color codes](https://www.digminecraft.com/lists/color_list_pc.php).
At some point, I plan to add a `/itemfactory name <name>`, which would rename the item to the supplied name. Importantly, this supplied name would support the `&` formatting system. For example:
`/itemfactory name &c&nSome Name`
Would be the formatting code equivalent of the nbt above.

**Comment by mega12345mega** [comment]
In the v1.9.0 update, I have now released the `/itemfactory name` feature mentioned above. For information on the specifics of the formatting system, refer to `/get help textformat`. This new feature also applies to the lore and signature commands.
For users who want to use the previous JSON system, there is now a config option.
