### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by AdminHcat** [mega12345mega/NBT-Editor#2]
1、The content input box can only hold 1000 characters(Although you can click for further editing, you still want to optimize it)
![image](https://user-images.githubusercontent.com/50044729/148699135-b455c576-8d07-4fbc-8993-d240a25ca9c8.png)
2、When the screen size is > 2, the text on the button cannot be clearly seen
![image](https://user-images.githubusercontent.com/50044729/148699374-ed4ed5a5-cd42-4e29-9302-620544f4edb7.png)

**Comment by mega12345mega** [comment]
Thanks for reporting these issues!
I just sent out v1.2.0, which fixes them. The character limit was removed, and there is an option accessible via the Mod Menu mod that allows you to change the text size.
