### ISSUE TITLE
The Expand menu doesn't show data properly

### ISSUE THREAD

**Issue by MattisPower** [mega12345mega/NBT-Editor#20]
If I expand any data in the net menu I can't see any of them unless the string is really long. But even then the first part of it is cut off. It seams like there is a big rectangle hiding the text but i really don't know how to remove it.
<img width="1258" alt="Bildschirmfoto 2022-10-04 um 18 11 01" src="https://user-images.githubusercontent.com/115027760/193871149-dd26ad87-47ac-4fe9-94c8-7c4c84088fff.png">

**Comment by mega12345mega** [comment]
If you enable the key fix in /nbteditor config, does it fix this?

**Comment by MattisPower** [comment]
I have this already enabled, because I work with a Mac. By the way the key fix isn’t the problem either, because if I disable it and click an the invisible buttons I have the same issue.

**Comment by mega12345mega** [comment]
I just figured out the issue:
While working the latest update, I realized that the MultiLineTextFieldWidget didn't check the key fix.
I have already fixed it in the development code, and the fix should be out in the next update.
I had just forgotten about it :/

**Comment by MattisPower** [comment]
I read #6 before, because I had the same problem. Thank you very much.

**Comment by mega12345mega** [comment]
I've just released v1.9.0, which fixes this problem. (I don't have a Mac, so I can't guarantee that.)
The update also renames the config option to "Mac Border Patch," and makes it automatically enabled for new Mac users.
