### ISSUE TITLE
Mod doesn't work

### ISSUE THREAD

**Issue by Domasgtuz** [mega12345mega/NBT-Editor#21]
I've tried every version, nothing. Are there any dependencies?

**Comment by mega12345mega** [comment]
Like most Fabric mods, this mod requires [Fabric API](https://www.curseforge.com/minecraft/mc-mods/fabric-api).
I had forgotten to add it as a dependency on [curseforge](https://www.curseforge.com/minecraft/mc-mods/nbt-editor), so I have now done that.

If that doesn't work, what version of Minecraft are you using?
v1.8 only supports Minecraft Fabric 1.19-1.19.2
v1.5 only supports Minecraft Fabric 1.17-1.18.1 (possibly 1.18.2, unsure)

If that does work, you can go ahead and close the issue.

**Comment by mega12345mega** [comment]
Closing since it has been almost a year.
