### ISSUE TITLE
conflict with held item info 

### ISSUE THREAD

**Issue by PixelAxolotl4702** [mega12345mega/NBT-Editor#24]
https://crashy.net/JkSPHncIx4iATKQK5t3O
https://bytebin.lucko.me/7jfKiMKYD6
the error i got :>

**Comment by mega12345mega** [comment]
I'm going to need a bit more information on how this crash occurred.
Did you do some action which crashed the game, or did it crash on startup?
And if possible, are you able to replicate this crash on 1.19 Minecraft versions? It seems to be related to 1.18 support.
Screenshots can also be helpful.

Thanks! Sorry for taking so long to respond.

**Comment by mega12345mega** [comment]
I believe I have found the issue and it should be corrected in the next update. However, I don't know how to reproduce it, so I can't test the fix.

**Comment by PixelAxolotl4702** [comment]
It seems to happend when I hold an item

**Comment by mega12345mega** [comment]
I've fixed this in the latest version, v1.9.1.
I wasn't able to get the game to crash when holding an item, so it might be inconsistent. Hopefully this has fixed it regardless.
