### ISSUE TITLE
Support: Move .nbt files to the mod

### ISSUE THREAD

**Issue by KahpotVanilla** [mega12345mega/NBT-Editor#27]
Hey, is there a way to put my .nbt file into the client chest?

**Comment by mega12345mega** [comment]
If your `.nbt` file is for an item, you can use an external editor like [NBTExplorer](https://github.com/jaquadro/NBTExplorer/releases) to open both a client chest page and the item. Keep in mind that client chest pages are zero-indexed, so page 1 is "page0.nbt". You will have to add an item to a page to get the file to appear in the folder. The client chest files are stored in `<game directory>/nbteditor/client_chest/`.

I have plans to possibly add importing `.nbt` files directly.

**Comment by mega12345mega** [comment]
In the latest update (v1.10.0), I have now included official support for this! Drag any `.nbt` file onto an inventory screen to get the item. Alternatively, you can drag the file into the editor, which adds the contents of the file to the current item being edited. To compliment this feature, `/nbt export file` has been added, which saves the item you're holding into a new `.nbt` file, located in `<game directory>/nbteditor/exported/`.
