### ISSUE TITLE
Attribute and enchant factories should have a more obvious option to delete entries

### ISSUE THREAD

**Issue by HyperSoop** [mega12345mega/NBT-Editor#28]

**Comment by mega12345mega** [comment]
This feature already exists (though it is hard to find). If you right click on the bar to the left of the enchantment or attribute entry, it will open a menu that allows you to remove it.

**Comment by HyperSoop** [comment]
~~Oh well that's why left clicking all over the place didn't help~~

**Comment by mega12345mega** [comment]
I would like to make this feature more obvious, but I'm not sure how to do that.
Maybe I could add the triple dot icon (⋮) to the bar?

**Comment by mega12345mega** [comment]
I've added the triple dot icon to the bar in the latest update (v1.10.0). Additionally, you can now left click the blue part of the bar to open the menu as well. (Left clicking on the black sections still moves the entry up and down.)
