### ISSUE TITLE
Make itemfactories accessible from the main "/nbt" menu for an item

### ISSUE THREAD

**Issue by HyperSoop** [mega12345mega/NBT-Editor#29]

**Comment by mega12345mega** [comment]
I believe from the comments on the mod there was a suggestion about a GUI for item factories. I'll add a button that opens up this GUI in the editor menu.

**Comment by mega12345mega** [comment]
I've just released v1.11.0, which adds this! In the top right corner of all item factory guis (+ the nbt editor and container menu), there is now a factory icon which opens a list of all the item factories with guis. Additionally, the keybind `Shift + Space` will open this gui just like the `Space` and `Ctrl + Space` keybinds.
