### ISSUE TITLE
Autocomplete possible key names

### ISSUE THREAD

**Issue by HyperSoop** [mega12345mega/NBT-Editor#31]
Simular to how command completion works, it would suggest possible names when adding new nbt entries and let you cycle through them. It would elluminate the need for obscure item factories since you'd be able to add any data to any item without precisely knowing the keys' names as long as vanilla or any mod has them registered.

**Comment by mega12345mega** [comment]
I have gotten this suggested before, and I have started looking into it! I'm unclear how easy it is going to be to get a list of all the usable keys, so this may take longer than expected. It would be a very useful feature.

**Comment by HyperSoop** [comment]
yeah, and they'd need to only be suggested in directories where they belong and would take effect. This feature would be worthy of a 2.0 release.

**Comment by mega12345mega** [comment]
I've finally released this in v1.13.0! It requires [NBT Autocomplete](https://modrinth.com/mod/nbt-autocomplete) to be installed at the same time. In addition to suggesting tag names in the "+" prompt, it also suggests stuff in the value editor and expand editor.
