### ISSUE TITLE
Support saving duplicate enchant types in the enchants itemfactory

### ISSUE THREAD

**Issue by HyperSoop** [mega12345mega/NBT-Editor#33]
Minecraft handles adding 2 sharpness enchants on a sword just fine, but the itemfactory for enchants doesn't handle this well, only letting 1 enchant of each type to be saved on an item. Adding multiple enchants of the same type on an item could actually be useful to bypass the 255-level cap, so this should be allowed in the itemfactory
![javaw 2023-02-05 09-21-26](https://user-images.githubusercontent.com/85982640/216804930-e0657d38-0b12-4bbf-ada3-01483a42fd48.png)

**Comment by mega12345mega** [comment]
I didn't realize that duplicating the same enchantment caused it to stack like that, that's pretty cool. I'll look into adding this. It might be more practical to have a "number of duplicates" field, so they are all condensed into one entry.

**Comment by HyperSoop** [comment]
> I didn't realize that duplicating the same enchantment caused it to stack like that, that's pretty cool. I'll look into adding this. It might be more practical to have a "number of duplicates" field, so they are all condensed into one entry.

I don't think a whole new field for the number of duplicates is needed, the thing is still pretty niche. It's more of a thing to just change so it can save with duplicate enchantments and maybe add a number input to the "duplicate" option

**Comment by mega12345mega** [comment]
I've just released v1.11.0, which adds this! The enchantment gui now supports the same enchantment listed multiple times, and shift clicking the "Duplicate" option allows you to specify any number of copies.
