### ISSUE TITLE
Error java.lang.ArrayIndexOutOfBoundsException when using client chest

### ISSUE THREAD

**Issue by BackslashG** [mega12345mega/NBT-Editor#36]
Whenever I open the client chest on a multiplayer server, it gives an error message:
`Internal Exception: java.lang.ArrayIndexOutOfBoundsException: Index 8 out of bounds for length 4`
I am using 1.19.3 and I don't know if I'm doing something wrong.

**Comment by mega12345mega** [comment]
Can you send the full log? Thanks. I'm assuming this occurs on all multiplayer servers?

**Comment by BackslashG** [comment]
Here's the [log](https://github.com/mega12345mega/NBT-Editor/files/10734793/latest.log), and it happens on all servers.

**Comment by mega12345mega** [comment]
Is that the correct log? It doesn't look like there is any exception. It might be in the `crash-reports` folder instead, it's possible that log files don't contain crashes.

I've just attempted to use the client chest, and I was unable to reproduce this error. It is very likely the mod is conflicting with a different mod you have loaded. Try having only NBT Editor in the mods folder. If it doesn't crash, do a binary search to find which mod is the culprit. (Add half, if it crashes remove a quarter, if it works add another quarter, etc.) You will probably find a mod which when added causes the crash, but when removed doesn't cause the crash.

**Comment by BackslashG** [comment]
Sorry, it seems like it's working now, not sure why.
