### ISSUE TITLE
Feature/improvements to editor interface

### ISSUE THREAD

**Issue by sudofox** [mega12345mega/NBT-Editor#4]
Hi! So I have a few suggestions at the moment.

1) A better interface for editing NBT lines, perhaps with a multiline input box with syntax highlighting? It's difficult to view/edit long lines and I don't seem to be able to scroll the actual viewed text left/right with my arrow keys, only my position on it (that is, the keyboard cursor moves "out of frame"). It would be GREAT to have it so you can prettify the nbt for easy-on-the-eyes editing!

2) A proper way to import/export to/from the client chest to the editor screen

**Comment by mega12345mega** [comment]
I've already started looking into multiline editing, but it seems like it is somewhat complicated, and I have yet to find a good library, so it might take a while to be created.

For the client chest & editor screen thing, are you talking about like a keybind that directly opens an item in the client chest in the editor, so you don't have to take it out and hold it first?

**Comment by sudofox** [comment]
Yes, something like that. Or being able to open and "save as" to make a variation.

**Comment by mega12345mega** [comment]
Just uploaded v1.3.0, which of the things mentioned in this issue includes: a formatting system; multi-line editor (expand button); space to edit an item in your inventory, client chest, or /open menu; and ctrl + space to open a container in your inventory, client chest, or /open menu.
You can always copy an item before you open it to replicate the functionality of a "save as" button.
