### ISSUE TITLE
Incompatibile with Journey map on 1.19.3

### ISSUE THREAD

**Issue by the456gamer** [mega12345mega/NBT-Editor#40]
https://gist.github.com/the456gamer/389ae6fb4d0744980fb883a250a9ecba

journeymap 5.9.3  
NBT Editor 1.10.0 

crash occurs after opening fullscreen map with "j" in a single player world

https://github.com/TeamJM/journeymap/issues/575

**Comment by mega12345mega** [comment]
I've just released v1.11.0, which fixes this!
