### ISSUE TITLE
Opening the client chest kicks you from some servers

### ISSUE THREAD

**Issue by HyperSoop** [mega12345mega/NBT-Editor#41]
Opening the client chest on some servers causes an index out of bounds error, i'll attack a log in a bit. (This should not depend on the server at all, it's in the name, what's going on?)

**Comment by mega12345mega** [comment]
Without a log it is hard to be sure, but my current guess is that the server is sending item packets to unusual slots. The mod has to do some sketchy math to update the client chest when picking up items while the server doesn't know that the chest is open. It is possible some slot isn't properly handled, causing it to write to an invalid location.

**Comment by HyperSoop** [comment]
I forgot to reproduce and send the log lol

**Comment by mega12345mega** [comment]
Have you had a chance to get a log? Thanks.

**Comment by HyperSoop** [comment]
aaaaa i should force myself to try and replicate it

**Comment by HyperSoop** [comment]
There doesn't appear to be a log message for somer reason.
![2023-03-29_08 46 50](https://user-images.githubusercontent.com/85982640/228449040-af1f027d-ea83-4d40-990c-eb04a7485a21.png)

**Comment by HyperSoop** [comment]
Steps to reliably reproduce:

- Join `BuildersDen.minehut.gg`  
- Do `/chest`
- You'll get kicked with "index 8 out of bounds for length 4"

**Comment by mega12345mega** [comment]
I've had a chance to replicate the issue. It appears that the server is sending a slot update packet for slot id 0 and sync id 0, which is breaking the client chest menu things. I'm currently figuring out what this is supposed to correspond to. In the meantime, you could use `/nbt export file` to get items to and from the server.

**Comment by mega12345mega** [comment]
I've just released v1.11.0, which fixes this! I eventually decided to discard the invalid packet from the server, since it didn't seem to correspond to anything anyway.
