### ISSUE TITLE
Incompatible with Minecraft 1.19.4

### ISSUE THREAD

**Issue by shaijana** [mega12345mega/NBT-Editor#42]
Hey,
please update the mod to the newest version of Minecraft.

Thank you!

**Comment by mega12345mega** [comment]
Progress:
- [x] Change to 1.19.4, check compile errors
- [ ] Move compile errors to the `multiversion` package
- [ ] Fix errors using reflection
- [ ] Fix mixins
- [ ] Test and get 1.19.4 working completly
- [ ] Fix all the new issues in 1.18.0 - 1.19.3

**Comment by mega12345mega** [comment]
I've just released v1.11.0, which now supports 1.19.4! Thanks for your patience.
