### ISSUE TITLE
Image to Lore

### ISSUE THREAD

**Issue by mega12345mega** [mega12345mega/NBT-Editor#45]
### Discussed in https://github.com/mega12345mega/NBT-Editor/discussions/43

<div type='discussions-op-text'>

<sup>Originally posted by **BenskuPro** April 22, 2023</sup>

<img width="1440" alt="Снимок экрана 2023-04-22 в 13 04 44" src="https://user-images.githubusercontent.com/131523313/233777634-91992358-eab9-451b-b6da-23cb7506f656.png">
Im asking how to do this
Im not 100% sure that its made by this mod, but i somehow made it before. But i forgot how to do it</div>

**Comment by HyperSoop** [comment]
[I think this mod has the feature.](https://modrinth.com/mod/fzmm)  It's open source too, so you can check how they do it.

**Comment by mega12345mega** [comment]
I've finally released this feature in v1.12.0. Drag the image onto the inventory screen (like .nbt files) for a new item, drag onto the new display gui to append to the current lore, and drag onto a book to append to the current page.
