### ISSUE TITLE
1.20 Support (v1.12.1)

### ISSUE THREAD

**Issue by mega12345mega** [mega12345mega/NBT-Editor#49]
Since I've been working on an update for a while, I'm planning on releasing that update without 1.20 support, then include 1.20 support in a follow-up update.

It's possible that 1.20 will be especially difficult due to the `MatrixStack` -> `DrawContext` change, if I plan to continue supporting all versions in one `.jar` file and codebase.

**Comment by Neodyminus** [comment]
heyo!
Thanks so much!!!

This is great, really appreciate it. take your time!
Do you have an ETA on 1.20?

**Comment by mega12345mega** [comment]
It's impossible to have an exact time estimate, especially with the nature of this update, since I'm not 100% my current approach is going to work. That said, I did a bunch of work yesterday and was able to achieve this:
* 1.20 was successfully launched
* 1.17 was successfully launched

However:
* 1.20 rendering was problematic (refer to the image below)
* 1.17 rendering crashed the game

Since I've decided to start committing between updates and push those commits, you will be able to access 1.20 as soon as it is somewhat stable in that version specifically, even before I've officially released the update. (Make sure to save items regularly and expect crashes.) If you check Github, once I've pushed the code, it should appear on a `mc_1.20` branch with the build attached as an artifact (for the latest commit, click on the green checkmark, then details, then summary).

I anticipate anywhere from today to several days from now for a version working in 1.20, and then an unknown amount of time for an official release.

![2023-06-22_02 22 55](https://github.com/mega12345mega/NBT-Editor/assets/55769873/f2a21ba3-a607-42cb-b202-59bef9af7202)

**Comment by mega12345mega** [comment]
There is now an in-development version of 1.20 support available: [https://github.com/mega12345mega/NBT-Editor/actions/runs/5352330217](https://github.com/mega12345mega/NBT-Editor/actions/runs/5352330217)
Download the artifacts `.zip` file, and then you probably want `libs/nbteditor-1.12.999.jar`.

Keep in mind, this version has had *minimal* testing. It may crash. It may render strangely. **BACK UP YOUR ITEMS**. You should copy the `client_chest` folder stored in `<game directory>/nbteditor` to somewhere safe.

**Comment by mega12345mega** [comment]
I've just released v1.12.1, which includes support for 1.20 and 1.20.1!
