### ISSUE TITLE
Breaks 'clientcommands' mod and crashes game

### ISSUE THREAD

**Issue by Eczbek** [mega12345mega/NBT-Editor#51]
Using `clientcommands` and `fabric-api` and `nbteditor` makes the game crash whenever a command provided by `clientcommands` is run.
[crash-2023-06-09_12.08.02-client.txt](https://github.com/mega12345mega/NBT-Editor/files/11708329/crash-2023-06-09_12.08.02-client.txt)

**Comment by Eczbek** [comment]
Sorry, here is the crash log
[crash-2023-06-09_12.08.02-client.txt](https://github.com/mega12345mega/NBT-Editor/files/11708319/crash-2023-06-09_12.08.02-client.txt)

**Comment by HyperSoop** [comment]
Can confirm, has been an issue for a long while, never knew why it happened, thought clientcommands was broken

**Comment by mega12345mega** [comment]
I've just released v1.12.0, which fixes this!

**Comment by Eczbek** [comment]
omgosh thanks
