### ISSUE TITLE
Can I change the location of this button?

### ISSUE THREAD

**Issue by minxwbs** [mega12345mega/NBT-Editor#58]
![image](https://github.com/mega12345mega/NBT-Editor/assets/107277366/c6885e64-ab3f-448a-b43a-f618daff9e49)
When i open my inventory

**Comment by mega12345mega** [comment]
It is not currently possible to change the location of the button. Can you specify the use case so I can better determine how I might add this? For example, is it conflicting with another mod, or you would just prefer it in a different corner? Adding a fully adjustable system (like overlay mods) would be more complicated, and something like an alignment dropdown (with left, center, right) could be easier to use.

**Comment by Wionsito** [comment]
> It is not currently possible to change the location of the button. Can you specify the use case so I can better determine how I might add this? For example, is it conflicting with another mod, or you would just prefer it in a different corner? Adding a fully adjustable system (like overlay mods) would be more complicated, and something like an alignment dropdown (with left, center, right) could be easier to use.

In my case, it's conflicting with JEI bookmarks button.

![Image](https://github.com/mega12345mega/NBT-Editor/assets/82771944/ba86f722-f8ba-47fc-9b05-91b3e1023278)

**Comment by Ghoster12154** [comment]
> > It is not currently possible to change the location of the button. Can you specify the use case so I can better determine how I might add this? For example, is it conflicting with another mod, or you would just prefer it in a different corner? Adding a fully adjustable system (like overlay mods) would be more complicated, and something like an alignment dropdown (with left, center, right) could be easier to use.
> 
> In my case, it's conflicting with JEI bookmarks button.
> 
> ![Image](https://private-user-images.githubusercontent.com/82771944/262782353-ba86f722-f8ba-47fc-9b05-91b3e1023278.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzQ0NDgsIm5iZiI6MTcxNzA3NDE0OCwicGF0aCI6Ii84Mjc3MTk0NC8yNjI3ODIzNTMtYmE4NmY3MjItZjhiYS00N2ZjLTliMDUtOTFiM2UxMDIzMjc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEzMDIyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlZTZkZjA4ZjUxZGJkYTNkZWExOWNjZmU4MzdiNDU1NWRlMmZmYjA3ZWEyYTNjMjA3MmM2Nzg4ZTdjODg2YTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z7nCPFh2pbYlHMEKxw80ldEoNCsopHMJ89dfO8maKcs)

same problem

**Comment by mega12345mega** [comment]
I've now added this as a config option (`/nbt config`) which lets you move the tabs to the left, center, or right, on either the top or bottom of the screen! (v2.0.1)
