### ISSUE TITLE
Open suspicious items and chiseled bookshelves like shulkers

### ISSUE THREAD

**Issue by MrT189** [mega12345mega/NBT-Editor#62]
In 1.20 new items were added that you can put any item into with nbt. It would be nice if you could open these so it is easier to edit their storage.

**Comment by mega12345mega** [comment]
I forgot to add chiseled bookshelves! Can you clarify what you mean by "suspicious items"?

**Comment by MrT189** [comment]
i should have been more specific. I am talking about suspicious sand and gravel.

**Comment by mega12345mega** [comment]
I've now released this in v1.13.0, along with the decorated pot! I've manually "fixed" [MC-48453](https://bugs.mojang.com/browse/MC-48453) by updating the block state of the chiseled bookshelf when the contents is changed.
