### ISSUE TITLE
Allows opening ender chests

### ISSUE THREAD

**Issue by hyplant** [mega12345mega/NBT-Editor#65]
Allows opening ender chests. 
 
Players can open their own ender chests by placing the mouse over the ender chest item and pressing CTRL + SPACE.
Or use the command /open to open ender chests when holding it in hand.

**Comment by mega12345mega** [comment]
While I would love to implement this (and maybe even re-purpose the enderchest "tab" for the actual enderchest, and have a different client chest tab), unfortunately the client doesn't have a way to read or write to the enderchest without placing it down and manually opening it. However, I can add this to the list of things to add if I ever make an optional server-side integration for this mod.

**Comment by mega12345mega** [comment]
I've added this in a dev build, where you can access the ender chest via `/open echest` or a new tab in the bottom left of the inventory and client chest. I haven't added it as an official "container," meaning it doesn't support `Ctrl+Space` or `/open`. Let me know if you think I should still add that part!

**Comment by mega12345mega** [comment]
I've now added this in v2.0.0!
