### ISSUE TITLE
Polish language support

### ISSUE THREAD

**Issue by Xantrisse** [mega12345mega/NBT-Editor#72]
Hello!
Is it possible to add a translation into Polish?

If so, I can send the translated file :D

**Comment by itsTyrion** [comment]
If you translate it, probably.

if you don't know the "correct" way to do this with git: 
- use the 'fork' option to create your copy of the project
- add the `pl_PL.jsin` language file, this can be done in the browser.
- open a pull request here so the dev can accept it or request changes, if needed

**Comment by Xantrisse** [comment]
https://github.com/Xantrisse/NBT-Editor-Mod-Polish-translation

**Comment by mega12345mega** [comment]
This looks good! I'll make sure to include the language file in the next update. Thanks!

**Comment by mega12345mega** [comment]
This has just been released in 1.12.2! Thanks for the translation.
