### ISSUE TITLE
Minecraft Crashed (Video) + 2Byte translation update lol

### ISSUE THREAD

**Issue by Xantrisse** [mega12345mega/NBT-Editor#75]
**I only added a color change because I forgot about it when translating the file:** https://github.com/Xantrisse/NBT-Editor-Mod-Polish-translation

**### Crash:**
[crash-2024-01-07_14.29.15-client.txt](https://github.com/mega12345mega/NBT-Editor/files/13853622/crash-2024-01-07_14.29.15-client.txt)

**### Video:**
https://github.com/mega12345mega/NBT-Editor/assets/149414796/03e89e5b-3d3c-4d6c-8c0e-753ed9e08f8f

**Comment by mega12345mega** [comment]
It looks like the crash is the same as Issue #74, where scrolling in non-scrollable parts of the GUI causes a crash. However, the user reporting the issue noted that it does occur in *some* scrollable GUIs (in their case it was provided by a different mod, just like here). Depending on how the Chest Tracker mod here is implemented, you may be able to scroll by manually dragging the scroll bar until I fix this.

**Comment by mega12345mega** [comment]
Everything here has been released in v1.13.0!
