### ISSUE TITLE
Display of item size in game

### ISSUE THREAD

**Issue by Xantrisse** [mega12345mega/NBT-Editor#77]
Display of item size in game (Can be set to Bytes, KiloBytes or MegaBytes)
![ugeij2sgdit31](https://github.com/mega12345mega/NBT-Editor/assets/149414796/48e69d2a-e3ef-437b-8020-7571c7fd172f)

**Comment by mega12345mega** [comment]
This seems interesting! There are a couple of config options that I could implement. What do you think I should bother making configurable, what should the defaults be, and if not configurable what should it be set to?
* Compressed or Uncompressed: `/nbt export file` exports items in the compressed format
* Kilobyte or Kibibyte (& mega, giga, etc. equivalent)
* Automatic prefix changing: switching between B, K(i)B, M(i)B, etc. automatically depending on item size

**Comment by Xantrisse** [comment]
Ideally it would show the uncompressed size of the item. If there is a string of, for example, 20 characters, the description will say "NBT Size: 20B" or something like that. Possibility to include real size or compressed size.
Display types: Bytes, Kilobytes, Megabytes, AUTO

Suggested Default Settings:
- Default display type: AUTO
- Compressed: No

*The AUTO display type will automatically change the display depending on the size of the item.

**Comment by mega12345mega** [comment]
I've now released this v1.13.0! It is off by default, but can be enabled in /nbt config.

*Warning:*
If anyone does what I obviously immediately did, which is attempting to create absurdly large items with recursive containers, keep in mind:
* Very large items in your inventory will prevent Minecraft from loading the world (use an external editor like NBT Explorer to unbrick)
* While the client chest seems to handle large items great, *unlike /nbt export, it does NOT use the compressed format*, so my 20 GB shulker box ended up taking 20 GB on the disk
