### ISSUE TITLE
Out Of Memory

### ISSUE THREAD

**Issue by HyperlightDrifta** [mega12345mega/NBT-Editor#79]
I have quite a few mods but it keeps giving me a java.lang.OutOfMemoryError: Java heap space error. Any help?

**Comment by itsTyrion** [comment]
> Any help?

how? you provided ZERO info. (and it's probably not related to NBT-Editor)

ow much RAM is allocated to MC? Which MC Version? What mods? Log? (https://mclo.gs)

**Comment by HyperlightDrifta** [comment]
I just updated the game lol.
