### ISSUE TITLE
Command argument text not shown when using NBT-Editor

### ISSUE THREAD

**Issue by Vulnerab1lity** [mega12345mega/NBT-Editor#86]
With NBT-Editor:
![image](https://github.com/mega12345mega/NBT-Editor/assets/42952817/3695c3c8-6c50-4912-aa30-355d50a34810)

Without NBT-Editor:
![image](https://github.com/mega12345mega/NBT-Editor/assets/42952817/6ddb5a32-28bc-461e-b64c-59b45e075331)

**Comment by Xantrisse** [comment]
I had the same situation but with the /achievement command.

**Comment by mega12345mega** [comment]
I've now fixed this in v2.0.0!
