### ISSUE TITLE
chest file got corrupted

### ISSUE THREAD

**Issue by BNectarie** [mega12345mega/NBT-Editor#87]
a page of my /chest got corrupted and it said it was backed up but i dont know how to get it back can someone help?

**Comment by mega12345mega** [comment]
The corrupted file is stored in the same folder as the normal client chest pages: `<game directory>/nbteditor/client_chest`. The page numbers are 0-indexed, meaning page 1's file name is `page0.nbt`, page 2's file name is `page1.nbt`, etc.

Before doing anything, I recommend copying the corrupted file to outside the game directory in case something unexpected happens. I would also recommend not running the game. The reload button on the page might be more convenient, but this might complicate things in unexpected ways.

Restoring the page isn't going to be as straightforward as renaming the corrupted page back to a normal page.
There should be an error being printed out in the console and logs that could indicate how the file is corrupted (this error only appears when trying to load it before realizing the page is corrupt, so you would need to rename the corrupted page back to a normal page). I'm not aware of any NBT file restoring tools, but that may exist.

Did anything weird happen before the page was corrupted? Like a game crash, computer bluescreen, or putting huge amounts of data in the page? If there is too much data, you may need to increase Minecraft's ram and rename the page back. You could also use an external tool like NBT Explorer to manually move some of the items to a different page. If the file's data itself is truly corrupted, you may need to manually edit the file using a hex editor. [https://wiki.vg/NBT](https://wiki.vg/NBT) appears to layout the NBT file format.

If you decide that the items aren't worth the effort, simply delete the corrupted file and the error will go away. If the file's data itself is corrupted, the items are important, and you're not comfortable attempting to recover it with a hex editor, you could post it here and I could take a look at it.

**Comment by BNectarie** [comment]
i found the problem why it was corrupted i put too much nbt weight and it corrupted
