### ISSUE TITLE
Move client chest button to the right for JEI compatibility

### ISSUE THREAD

**Issue by voidapex11** [mega12345mega/NBT-Editor#90]
I use nbt editor with JEI And the nbt editor client chest overlaps with the jei bookmarks button.

could you add an ability to customize the location of the client chest button or move the button to the right.

**Comment by mega12345mega** [comment]
This should be covered by #58

**Comment by mega12345mega** [comment]
I've now added this in v2.0.1 (see the original issue for details)!
