### ISSUE TITLE
Weird crash report when opening up client chest thingy

### ISSUE THREAD

**Issue by Fnige** [mega12345mega/NBT-Editor#92]
Log: https://gist.github.com/Fnige/bfc863549284cdf953d5575b7fe2e30c

Basically all I had to do is open up the client chest and it seemed to crash.
There was also errors about files not existing too which you can see [here](https://gist.github.com/Fnige/bfc863549284cdf953d5575b7fe2e30c#file-crash-log-L1608) so maybe thats related to the issue?

**Comment by mega12345mega** [comment]
It seems like the mod is failing to create the `page_names.json` file, which is where the names for the client chest pages are stored. I don't know why this would happen - is your hard drive full, or does the game directory have write access restrictions? You could try manually creating the file in `<game directory>/nbteditor/client_chest/page_names.json` with the contents `{}`. (If this fixes it, I imagine setting pages names would cause an error when trying to write to it again.)

**Comment by Fnige** [comment]
Interestingly enough adding the file seems to have fixed all of the issues which is weird. Idk if this could happen with someone else so you can close the issue if you want

**Comment by mega12345mega** [comment]
Just in case, I'll add some code to explicitly create the file, since it might be some weird operating system thing or something that causes the current code to be ambiguous.

**Comment by mega12345mega** [comment]
I believe a dev build with a fix for this has been available for a while now, I just had forgotten to label the issue.
Looking at what I changed, it seems like the problem may have been that the `client_chest` folder was missing, so it was unable to create the `page_names.json` file inside of it. If you happen to still remember, can you confirm that when you created the file you also had to create the `client_chest` folder?

**Comment by Fnige** [comment]
My memory is nonexistant so sadly I do not remember but maybe?

**Comment by mega12345mega** [comment]
I've now fixed this in v2.0.0!
