### ISSUE TITLE
Game Crashing

### ISSUE THREAD

**Issue by toadwaawa** [mega12345mega/NBT-Editor#94]
"The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'nbteditor'!"

pops up when I run Minecraft, with the mod. It also does the same thing with IBE-editor, I don't know what the problem is but when I remove the mod from my mods folder, it gets fixed.

**Comment by mega12345mega** [comment]
I can't fix the problem without more information. Can you send the crash report or log file? (Contained within `<game directory/crash-reports` or `<game directory>/logs`)

**Comment by toadwaawa** [comment]
[crash-2024-03-29_14.35.12-client.txt](https://github.com/mega12345mega/NBT-Editor/files/14809776/crash-2024-03-29_14.35.12-client.txt)

**Comment by toadwaawa** [comment]
@mega12345mega you haven't responded is everything good?

**Comment by mega12345mega** [comment]
It looks like the `page_names.json` file might be corrupted somehow. Try deleting `<game directory>/nbteditor/client_chest/page_names.json` if you are ok with loosing any names you currently have (otherwise you will have to repair the file somehow).

If that isn't it, it might be related to #92.

**Comment by toadwaawa** [comment]
This seems to have fixed it. Thank you

**Comment by toadwaawa** [comment]
This seems to have fixed it, thank you.
