### ISSUE TITLE
Discord server because why not?

### ISSUE THREAD

**Issue by Xantrisse** [mega12345mega/NBT-Editor#97]
You can create a Discord server for people interested in this mod. Channels for conversations, proposals and discussions about changes that can be made in the modification. This is also a good way to keep your language translations up to date.

**Comment by mega12345mega** [comment]
Good idea! I've now done that: [https://discord.gg/PzeYTbEZjn](https://discord.gg/PzeYTbEZjn)
I've decided to keep bug reports and suggestions on Github, since they are easier to manage here

We'll see if anyone actually joins :)
